# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eRxFs6whIBxrYO6Foex3N20dQZfb8egx
"""

# Commented out IPython magic to ensure Python compatibility.
import sys
if 'google.colab' in sys.modules:
#   %pip install streamlit
import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

# 設定頁面資訊
st.set_page_config(page_title="Probe Card Mechanics Demo", page_icon="🔬", layout="wide")

st.title("🔬 Probe Card Mechanics: Why Isolated Pins Fail?")
st.markdown("""
此應用程式模擬探針卡在 **Wafer Edge (晶圓邊緣)** 的受力行為。
主要展示為什麼 **Isolated Pin (孤立針)** 比 **Grouped Pins (群組針)** 更容易發生偏位與變形。
""")

# Sidebar 控制項
st.sidebar.header("Simulation Settings")
scenario = st.sidebar.radio(
    "選擇情境 (Scenario):",
    ("Scenario A: Grouped Pins (Safe)", "Scenario B: Isolated Pin (Risk)")
)

show_force = st.sidebar.checkbox("Show Force Vectors (顯示受力)", value=True)

# 繪圖函數
def draw_mechanics(mode):
    fig, ax = plt.subplots(figsize=(10, 6))

    # --- 1. 繪製晶圓與 Pad (Wafer & Pads) ---
    # 定義晶圓輪廓 (包含平坦區與斜坡)
    x_wafer = np.linspace(0, 10, 100)
    # 斜坡從 x=8 開始
    y_wafer = np.array([2.0 if x < 8 else 2.0 - (x-8)*1.5 for x in x_wafer])

    # 填充晶圓區域
    ax.fill_between(x_wafer, 0, y_wafer, color='#E0E0E0', label='Wafer Substrate')
    ax.text(4, 1.0, "Silicon Wafer", color='gray', fontsize=12, ha='center')
    ax.text(9, 0.5, "Edge Bevel\n(斜坡)", color='gray', fontsize=10, ha='center', rotation=-45)

    # 繪製 Pads (金屬墊)
    if mode == 'Grouped':
        rect1 = patches.Rectangle((2, 2.0), 1, 0.2, linewidth=0, edgecolor='none', facecolor='#FFD700') # Pad 1
        rect2 = patches.Rectangle((4.5, 2.0), 1, 0.2, linewidth=0, edgecolor='none', facecolor='#FFD700') # Pad 2
        ax.add_patch(rect1)
        ax.add_patch(rect2)
        ax.text(2.5, 1.8, "Pad", ha='center', fontsize=9)
        ax.text(5.0, 1.8, "Pad", ha='center', fontsize=9)
    else:
        # Isolated 模式下沒有 Pad 在附近
        pass

    # --- 2. 繪製探針卡座 (Probe Head) ---
    head_color = '#444444'
    pin_color = '#000000'

    # 根據模式決定 Z 軸高度 (Overdrive 程度)
    # Grouped: 被 Pad 頂住，停在較高位置 (y=7)
    # Isolated: 沒人頂住，繼續下壓 (Overdrive)，降到 y=6
    head_y_bottom = 7.0 if mode == 'Grouped' else 6.0

    rect_head = patches.Rectangle((1, head_y_bottom), 8.5, 1.0, linewidth=0, facecolor=head_color, alpha=0.7)
    ax.add_patch(rect_head)
    ax.text(5.25, head_y_bottom + 0.4, "Probe Card Head (Ceramic/Space Transformer)",
            color='white', ha='center', fontsize=10)

    # --- 3. 繪製探針 (Needles) ---

    if mode == 'Grouped':
        # Pin 1 (Safe)
        ax.plot([2.5, 2.5], [2.2, head_y_bottom], color=pin_color, linewidth=3)
        # Pin 2 (Safe)
        ax.plot([5.0, 5.0], [2.2, head_y_bottom], color=pin_color, linewidth=3)
        # Pin 3 (Edge Pin - Safe because Head is stopped)
        # 針長固定，所以如果 Head 在 7.0，針尖約在 7.0 - 4.8 = 2.2 左右
        # 這裡畫它懸空或輕觸斜坡上方
        ax.plot([8.5, 8.5], [head_y_bottom - 4.8, head_y_bottom], color=pin_color, linewidth=3, linestyle='--')

        ax.scatter([2.5, 5.0], [2.2, 2.2], color='red', zorder=5, s=50) # Contact points

        status_text = "SAFE: Supported by neighbors"
        status_color = 'green'

        if show_force:
            # 畫支撐力箭頭 (Support Force)
            ax.arrow(2.5, 2.2, 0, 1.5, head_width=0.2, head_length=0.3, fc='blue', ec='blue', label='Support')
            ax.arrow(5.0, 2.2, 0, 1.5, head_width=0.2, head_length=0.3, fc='blue', ec='blue')
            ax.text(3.75, 4.0, "Reaction Force\n(Support)", color='blue', ha='center', fontweight='bold')

    else: # Isolated
        # Pin (Edge Pin - Risk)
        # Head 下降到 6.0 (Overdrive)
        # 針被壓彎了！
        # 起點 (Head): (8.5, 6.0)
        # 終點 (Wafer Edge): 滑移到 (9.0, 0.5) (假設滑下去了)
        # 中間彎曲點 (Buckling)

        # 使用貝茲曲線或簡單折線模擬彎曲
        # 這裡用簡單折線表示
        x_bent = [8.5, 8.3, 9.2] # Head -> Buckle -> Tip
        y_bent = [head_y_bottom, 3.5, 0.2] # Head -> Middle -> Slope

        ax.plot(x_bent, y_bent, color='red', linewidth=4)
        ax.scatter([9.2], [0.2], color='red', zorder=5, s=100, marker='x') # Crash point

        status_text = "FAIL: Needle Sliding & Bending!"
        status_color = 'red'

        if show_force:
            # 下壓力
            ax.arrow(8.5, head_y_bottom, 0, -1.5, head_width=0.2, fc='black', ec='black')
            ax.text(8.7, 5.0, "Overdrive\n(No Stop)", color='black', ha='left')

            # 側向滑動力
            ax.arrow(9.2, 0.2, 0.8, -0.8, head_width=0.2, fc='red', ec='red')
            ax.text(9.5, 0.5, "Slip / Skid", color='red', ha='left', fontweight='bold')

    # --- 4. 版面修飾 ---
    ax.set_xlim(0, 11)
    ax.set_ylim(-1, 9)
    ax.set_aspect('equal')
    ax.axis('off') # 隱藏座標軸

    # 標題與狀態
    plt.title(f"{mode} Configuration", fontsize=16, fontweight='bold')
    plt.text(5.5, -0.8, status_text, color=status_color, fontsize=14, fontweight='bold', ha='center',
             bbox=dict(facecolor='white', edgecolor=status_color, boxstyle='round,pad=0.5'))

    return fig

# Streamlit 呈現邏輯
col1, col2 = st.columns([1, 2])

with col1:
    st.info("### 📝 Engineering Note")
    if scenario == "Scenario A: Grouped Pins (Safe)":
        st.markdown("""
        **機制說明 (Mechanism):**
        * **Z-Stop Effect**: 內側的探針 (Pins 1 & 2) 穩固地接觸 Pad，提供了反作用力。
        * **Protection**: 這些反作用力阻止了 Probe Head 繼續過度下壓。
        * **Result**: 最外側的針 (Pin 3) 即使懸空或接觸邊緣，也不會承受過大的壓力。
        """)
    else:
        st.error("""
        **機制說明 (Mechanism):**
        * **No Support**: 孤立針周圍沒有鄰居提供支撐。
        * **Overdrive**: 機台持續下壓尋找接觸訊號。
        * **Sliding**: 針尖接觸斜坡 (Bevel) 時，垂直力轉為 **側向力 (Lateral Force)**。
        * **Result**: 針尖滑移 (Skid)，針身發生塑性變形 (Permanent Deformation)。這導致該針位未來測試時會產生 **Probe Mark Shift**。
        """)

with col2:
    mode_key = 'Grouped' if "Grouped" in scenario else 'Isolated'
    fig = draw_mechanics(mode_key)
    st.pyplot(fig)

st.write("---")
st.caption("Generated by Gemini Quality Engineering Assistant for Irene.")